version: '3.8'

services:
  pna-webserver:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    container_name: pna-webserver
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev