services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/www:/var/www/html
      - ./nginx/ssl:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pna-webserver
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/www:/var/www/html
      - ./nginx/ssl:/etc/letsencrypt
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'

  pna-webserver:
    build:
      target: production
    command: pm2-runtime start ecosystem.config.js